# -*- coding: utf-8 -*-
"""2505.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zAmJ62-d2Rmjf86RmjqY2jZyC3bQhuAC
"""

import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Dropout, Flatten
from keras.datasets import mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
print(x_train.shape, y_train.shape)

x_train= x_train.astype('float32')
x_test= x_test.astype('float32')
x_train/=255
x_test/=255

x_train= np.expand_dims(x_train, -1)
x_test= np.expand_dims(x_test, -1)

from keras.utils import to_categorical
y_train= to_categorical(y_train)
y_test= to_categorical(y_test)

model= Sequential()
model.add(Conv2D(32, kernel_size=(3,3), activation='relu', input_shape=(28,28,1)))
MaxPooling2D((2,2)),
Conv2D(64, (3,3), activation='relu'),
MaxPooling2D((2,2)),
Conv2D(64, (3,3), activation='relu'),
Flatten(),
Dense(64, activation='relu'),
Dense(10, activation='softmax')
model.summary()

from tensorflow.keras.layers import Flatten, Dense

model.add(Flatten())

model.add(Dense(10, activation='softmax'))

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=128, epochs=10, verbose=1, validation_data=(x_test, y_test))

import matplotlib.pyplot as plt
test_lost, test_acc= model.evaluate(x_test, y_test)
print('Test Accuracy: ', test_acc)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Model Accuracy')
plt.ylabel('Accuracy')
plt.xlabel('Epoch')
plt.legend(['Train', 'Validation'], loc='upper left')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# --- PHẦN BỔ SUNG ĐỂ SỬA LỖI ---
# Lấy bức ảnh đầu tiên (index = 0) từ tập x_test để dự đoán
img_gray = x_test[0]
img_ready = img_gray.copy()
# -------------------------------

# 1. Chuẩn hóa dữ liệu
img_ready = img_ready.astype('float32')
img_ready /= 255.0

# 2. Thêm chiều batch cho ảnh
img_input = np.expand_dims(img_ready, axis=0)

# 3. Dự đoán
preds = model.predict(img_input)
digit = np.argmax(preds)

# 4. Hiển thị kết quả
plt.imshow(img_gray, cmap='gray', interpolation='none')
plt.title(f'Dự đoán (Predict): {digit}')
plt.axis('off')
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# 1. Khởi tạo ảnh (Lấy ví dụ ảnh đầu tiên từ tập test)
# x_test có shape (10000, 28, 28, 1) sau khi expand_dims
img_gray = x_test[0]
img_ready = img_gray.copy()

# 2. Chuẩn hóa dữ liệu
# x_test đã được chuẩn hóa, nên không cần làm lại ở đây
# img_ready = img_ready.astype('float32')
# img_ready /= 255.0

# 3. Đưa về đúng định dạng 4D cho CNN: (1, 28, 28, 1)
# Sử dụng reshape để thêm chiều batch và giữ nguyên kích thước 28x28
img_input = img_ready.reshape(1, 28, 28, 1)

# 4. Dự đoán
preds = model.predict(img_input)
digit = np.argmax(preds)

# 5. Hiển thị kết quả
# Khi hiển thị bằng matplotlib, ta cần bỏ chiều channel đi, đưa về lại (28, 28)
plt.imshow(img_gray.reshape(28, 28), cmap='gray', interpolation='none')
plt.title(f'Dự đoán (Predict): {digit}')
plt.axis('off')
plt.show()

from keras.datasets import cifar10
(x_train, y_train) , (x_test, y_test) = cifar10.load_data()

x_train= x_train.astype('float32')/255
x_test= x_test.astype('float32')/255

from keras.utils import to_categorical
y_train= to_categorical(y_train,10)
y_test= to_categorical(y_test,10)

from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
model= Sequential()
model.add(Conv2D(32, (3,3),activation='relu', input_shape=(32,32,3)))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(64, (3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Conv2D(128, (3,3), activation='relu'))
model.add(MaxPooling2D((2,2)))
model.add(Flatten())
model.add(Dense(1000, activation='relu'))
model.add(Dense(10, activation='softmax'))
model.summary()

model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x_train, y_train, batch_size=200, epochs=5, verbose=1, validation_data=(x_test, y_test))

import numpy as np
import matplotlib.pyplot as plt

# ĐÃ SỬA: Nên dùng API công khai của Keras/TensorFlow thay vì keras.src (dùng cho nội bộ)
from tensorflow.keras.utils import load_img, img_to_array

# 1. Tải ảnh và hiển thị
img = load_img('/content/sieu-xe-dien-ferrari-dau-tien-2.jpg', target_size=(32, 32))
plt.imshow(img)
plt.axis('off')
plt.show() # Lưu ý: Nên hiển thị ảnh TRƯỚC khi chuyển đổi nó thành mảng (array)

# 2. Tiền xử lý ảnh (Logic của bạn rất chuẩn!)
# Đổi tên biến thành img_arr để không bị ghi đè mất bức ảnh gốc ở trên
img_arr = img_to_array(img)
img_arr = img_arr.reshape(1, 32, 32, 3)
img_arr = img_arr.astype('float32') / 255.0

# 3. Dự đoán
preds = model.predict(img_arr)
class_idx = np.argmax(preds, axis=-1)[0] # Lấy giá trị index dự đoán

# 4. Ánh xạ index sang tên các lớp của CIFAR-10
cifar10_classes = [
    'Máy bay (Airplane)', 'Ô tô (Automobile)', 'Chim (Bird)', 'Mèo (Cat)',
    'Hươu (Deer)', 'Chó (Dog)', 'Ếch (Frog)', 'Ngựa (Horse)',
    'Tàu thủy (Ship)', 'Xe tải (Truck)'
]

print(f"🎯 Kết quả dự đoán: {cifar10_classes[class_idx]} (Class {class_idx})")

from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

train_dir= '/content/drive/MyDrive/Nguyen Ngoc Bao'

img_width, img_height= 200, 200
batch_size = 32
# Tăng cường dữ liệu dành cho huấn luyện mô hình
train_datagen = ImageDataGenerator(
rescale=1.0/255, rotation_range=30, width_shift_range=0.2, height_shift_range=0.2, shear_range=0.2, zoom_range=0.2, horizontal_flip= True, fill_mode="nearest")

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Activation, Flatten, Conv2D, MaxPooling2D
from tensorflow.keras.preprocessing.image import ImageDataGenerator
import matplotlib.pyplot as plt

# Đường dẫn TRÙM chứa các thư mục con (Toi, Nguoi_Khac...)
train_dir = '/content/drive/MyDrive/Nguyen Ngoc Bao'

img_width, img_height = 200, 200
batch_size = 32

# 1. Khai báo bộ tăng cường dữ liệu
train_datagen = ImageDataGenerator(
    rescale=1.0/255,
    rotation_range=30,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode="nearest",
    validation_split=0.2 # LUÔN NHỚ: Phải bớt lại 20% ảnh để làm bài test
)

# 2. Bắt đầu đổ dữ liệu vào phễu
print("Chuẩn bị dữ liệu học...")
train_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='binary', # Dùng 'binary' nếu chỉ có 2 thư mục (Tôi vs Người khác). Dùng 'categorical' nếu có 3 thư mục trở lên.
    subset='training'
)

print("Chuẩn bị dữ liệu kiểm tra...")
val_data = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='binary',
    subset='validation'
)

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout

# 1. Tải dữ liệu huấn luyện (ĐÃ SỬA: class_mode="binary")
train_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode="binary",
    subset='training' # Cần có dòng này nếu bạn dùng validation_split ở trên
)

val_generator = train_datagen.flow_from_directory(
    train_dir,
    target_size=(img_width, img_height),
    batch_size=batch_size,
    class_mode='binary',
    subset='validation'
)

# 2. XÂY DỰNG MÔ HÌNH CNN
model = Sequential([
    Conv2D(32, (3,3), activation="relu", input_shape=(img_width, img_height, 3)),
    MaxPooling2D((2,2)),

    Conv2D(64, (3,3), activation="relu"),
    MaxPooling2D((2,2)),

    Conv2D(128, (3,3), activation="relu"),
    MaxPooling2D((2,2)),

    Flatten(),
    Dense(128, activation="relu"),
    Dropout(0.5),

    # ĐÃ SỬA: 1 nơ-ron, dùng sigmoid cho 2 class
    Dense(1, activation="sigmoid")
])

# 3. BIÊN DỊCH VÀ HUẤN LUYỆN (BỔ SUNG)
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

print("🧠 Bắt đầu cho AI học nhận diện khuôn mặt...")
history = model.fit(
    train_generator,
    epochs=15,
    validation_data=val_generator
)

print("🎉 XONG! AI đã học xong!")

import matplotlib.pyplot as plt

# 1. BIÊN DỊCH MÔ HÌNH (Đã sửa lại thành binary)
model.compile(optimizer="adam",
              loss="binary_crossentropy",
              metrics=["accuracy"])

# Tóm tắt cấu hình của mô hình
model.summary()

# 2. HUẤN LUYỆN MÔ HÌNH CNN
epochs = 10
print("🧠 Bắt đầu cho AI đi học...")
history = model.fit(
    train_generator,
    epochs=epochs,
    validation_data=val_generator # BẮT BUỘC PHẢI CÓ để lấy điểm val_accuracy
)

# 3. ĐÁNH GIÁ KẾT QUẢ MÔ HÌNH BẰNG BIỂU ĐỒ
# Đã có validation_data ở trên thì hàm vẽ này mới hoạt động được
plt.plot(history.history['accuracy'], label="Độ chính xác lúc học (Train)")
plt.plot(history.history["val_accuracy"], label="Độ chính xác lúc thi (Val)")
plt.xlabel("Số vòng học (Epochs)")
plt.ylabel("Độ chính xác")
plt.title("Biểu đồ quá trình thông minh lên của AI")
plt.legend()
plt.show()

# Tải và tiền xử lý ảnh kiểm tra
from tensorflow.keras.utils import load_img
import numpy as np
import matplotlib.pyplot as plt # Assuming plt is imported if not already

path = "/content/drive/MyDrive/Nguyen Ngoc Bao"
# Tiên đoán loại
img = load_img(path, target_size=(128, 128))
plt.imshow(img)
plt.show()
img = np.array(img)
img = img / 255.0
img = img.reshape(1, 128, 128, 3)
prediction=np.argmax(model.predict(img))
# Ánh xạ loại tới tên người
class_labels = {v: k for k, v in train_generator.class_indices.items()}
person_name = class_labels[prediction]
print(f"Người tiên đoán: {person_name}")

from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt

# 1. BẮT BUỘC SỬA: Trỏ thẳng vào 1 file ảnh cụ thể
path = "/content/artworks-Z7XDkvWMAGoxkPOV-Iym7SQ-t500x500.jpg"

# 2. ĐÃ SỬA: Kích thước phải khớp với mô hình đã học (200x200)
img = image.load_img(path, target_size=(200, 200))
plt.imshow(img)
plt.show()

# 3. Tiền xử lý ảnh
img_array = image.img_to_array(img)
img_array = img_array / 255.0
img_array = np.expand_dims(img_array, axis=0) # Dùng expand_dims cho an toàn thay vì reshape tay

# 4. ĐÃ SỬA: Dự đoán bằng Sigmoid (Phân loại 2 class)
xac_suat = model.predict(img_array)[0][0]

# Nếu xác suất > 0.5 thì là class 1, ngược lại là class 0
prediction = 1 if xac_suat > 0.5 else 0

# 5. Ánh xạ loại tới tên người
class_labels = {v: k for k, v in train_generator.class_indices.items()}
person_name = class_labels[prediction]

do_tu_tin_that = xac_suat if prediction == 1 else (1.0 - xac_suat)
print(f"🔮 Kết quả tiên đoán: {person_name}")
print(f"📊 Tỷ lệ tự tin của AI: {do_tu_tin_that * 100:.2f}%")

model.save("/content/drive/MyDrive/Nguyen Ngoc Bao/bo_nao_nhan_dien_mat.h5")